# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    - name: Static Analysis
      run: |
        go vet ./...
        golint .

    - name: Check Formatting
      run: if [ "$(gofmt -s -l ./src | wc -l)" -gt 0 ]; then exit 1; fi

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags='-w -s -extldflags "-static"' -tags netgo -o validator cmd/validator/validator.go

    - name: Test
      run: go test -v ./...
